version: 2

updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "dart"

  - package-ecosystem: "pub"
    directory: "/widgetbook"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "dart"

  - package-ecosystem: "npm"
    directory: "/site"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "npm"
    directory: "/mcp-server"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"
